; Available event IDs are listed in content/events/
; Check the banner images to identify each special event

; Warn: Xbox 360 did not receive the Colosseum map
; Using an event ID with this map cause crash

[Event]
Xbox360=2318
XboxUWP=2324

[Reward]
Enabled=true
TXID_01=TXDLI00451 ; Message on load screen
RewardSet=LotteryBuffSet_0B ; Param from ItemPackage.json
TicketNum=100 ; Amount of Happy tickets to give player
EndDate=20270101